import "primereact/resources/primereact.min.css"
import "primeicons/primeicons.css"
import 'primeflex/primeflex.css'
import '../../utils/styles/reset.css'
import '../../utils/styles/globals.css'

import Providers from '../../components/ui/withChildren/Providers'
import General from '@/components/servers-components/layouts/layout/General'
import { Locale, i18n } from '@/i18n.config'
import { Metadata } from 'next'

import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: {
        template: '%s | NEXT MGO',
        default: 'NEXT MGO',
    },
    description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => (
    <html lang={'en'} suppressHydrationWarning={true}>
        <head>
            {/* <link id="app-theme" href="/themes/md-light-deeppurple/theme.css" rel="stylesheet" /> */}
            <link id="app-theme" href="/themes/md-dark-deeppurple/theme.css" rel="stylesheet" />
        </head>

        <body className={inter.className + ' flex flex-column justify-content-between'} style={{ minHeight: '100vh' }}>
            <Providers>
                <General>
                    {children}
                </General>
            </Providers>
        </body>
    </html>
)
export default RootLayout



// import "primereact/resources/primereact.min.css"
// import "primeicons/primeicons.css"
// import 'primeflex/primeflex.css'
// import '../../utils/styles/reset.css'
// import '../../utils/styles/globals.css'

// import Providers from '../../components/ui/withChildren/Providers'
// import General from '@/components/servers-components/layouts/layout/General'
// import { Locale, i18n } from '@/i18n.config'
// import { Metadata } from 'next'

// import { Inter } from 'next/font/google'
// const inter = Inter({ subsets: ['latin'] })

// export async function generateStaticParams() {
//     return i18n.locales.map(locale => ({ lang: locale }))
// }

// export const metadata: Metadata = {
//     title: {
//         template: '%s | NEXT MGO',
//         default: 'NEXT MGO',
//     },
//     description: 'Generated by create next app',
// }

// const RootLayout = ({ children, params }: { children: React.ReactNode, params: { lang: Locale } }) => (
//     <html lang={params.lang} suppressHydrationWarning={true}>
//         <head>
//             {/* <link id="app-theme" href="/themes/md-light-deeppurple/theme.css" rel="stylesheet" /> */}
//             <link id="app-theme" href="/themes/md-dark-deeppurple/theme.css" rel="stylesheet" />
//         </head>

//         <body className={inter.className + ' flex flex-column justify-content-between'} style={{ minHeight: '100vh' }}>
//             <Providers>
//                 <General lang={params.lang}>
//                     {children}
//                 </General>
//             </Providers>
//         </body>
//     </html>
// )
// export default RootLayout