import "primereact/resources/primereact.min.css"
import "primeicons/primeicons.css"
import 'primeflex/primeflex.css'
import '@/utils/styles/reset.css'
import '@/utils/styles/globals.css'
import '@/utils/styles/theme.css'
import '@/utils/styles/chrome.css'

import Providers from '@/components/ui/withChildren/Providers'
import General from '@/components/servers-components/layouts/layout/General'
import { Locale, i18n } from '@/utils/language/i18n.config'
import { Metadata } from 'next'
import { Roboto } from 'next/font/google'
// import { findOneUserAction } from '@/utils/lib/mongodb/actions'

const roboto = Roboto({
    subsets: ['latin'],
    weight: ["100", "300", "400", "500", "700", "900"],
    style: 'normal',
})

export const metadata: Metadata = {
    title: {
        template: '%s | NEXT MGO',
        default: 'NEXT MGO',
    },
    description: 'Generated by create next app',
}

export async function generateStaticParams() {
    return i18n.locales.map(locale => ({ lang: locale }))
}

export const revalidate = 0

export default async function RootLayout({ children, params }: { children: React.ReactNode, params: { lang: Locale } }) {

    return (
        <html lang={params.lang} suppressHydrationWarning={true} data-theme='auto'>
            <body className={roboto.className + ' flex flex-column justify-content-between'} style={{ minHeight: '100vh' }}>
                <Providers>
                    <General lang={params.lang}>
                        {children}
                    </General>
                </Providers>
            </body>
        </html>
    )
}